export type StrategyCatalogEntry = { name: string; family: string; summary: string }

export const STRATEGY_CATALOG: StrategyCatalogEntry[] = [
  ['Opening Range Breakout', 'Momentum', 'Reviews a break from the defined opening range.'],
  ['Moving Average Crossover', 'Trend', 'Compares two moving averages at the recorded entry.'],
  ['MACD Cross', 'Momentum', 'Reviews a MACD line and signal-line crossover.'],
  ['RSI Reversion', 'Mean reversion', 'Checks an RSI move from an oversold or overbought zone.'],
  ['Bollinger Band Reversion', 'Mean reversion', 'Reviews price movement back toward the band midpoint.'],
  ['Bollinger Band Squeeze', 'Volatility', 'Checks a volatility contraction followed by expansion.'],
  ['Donchian Channel Breakout', 'Breakout', 'Reviews a break beyond a rolling price channel.'],
  ['Keltner Channel Breakout', 'Breakout', 'Checks price leaving an ATR-based channel.'],
  ['Trendline Break', 'Breakout', 'Reviews a confirmed break of a manually defined trendline.'],
  ['Support and Resistance', 'Price action', 'Checks reactions at recorded horizontal levels.'],
  ['Pullback to Moving Average', 'Trend', 'Reviews a trend pullback toward a moving average.'],
  ['Higher-Timeframe Alignment', 'Trend', 'Checks direction agreement across selected timeframes.'],
  ['ADX Trend Filter', 'Trend', 'Reviews directional movement with an ADX threshold.'],
  ['Parabolic SAR Trail', 'Trend', 'Checks entry direction against Parabolic SAR state.'],
  ['Supertrend', 'Trend', 'Reviews a Supertrend direction change.'],
  ['Ichimoku Cloud Breakout', 'Trend', 'Checks price and conversion signals relative to the cloud.'],
  ['Pivot Point Reversal', 'Mean reversion', 'Reviews a reaction around a daily pivot level.'],
  ['Fibonacci Retracement', 'Price action', 'Checks a reaction near a recorded retracement level.'],
  ['Fibonacci Extension', 'Price action', 'Reviews entry context against an extension level.'],
  ['VWAP Bounce', 'Intraday', 'Checks a bounce from volume-weighted average price.'],
  ['VWAP Fade', 'Intraday', 'Reviews a move back toward VWAP after extension.'],
  ['Anchored VWAP', 'Intraday', 'Checks price relative to an event-anchored VWAP.'],
  ['Volume Breakout', 'Volume', 'Reviews a range break with elevated volume.'],
  ['Relative Volume Spike', 'Volume', 'Checks entry context against typical volume.'],
  ['Accumulation/Distribution', 'Volume', 'Reviews price direction alongside money-flow pressure.'],
  ['On-Balance Volume', 'Volume', 'Checks OBV direction against price direction.'],
  ['Volume Profile Node', 'Volume', 'Reviews interaction with a high-volume price area.'],
  ['Gap and Go', 'Intraday', 'Checks continuation after a defined opening gap.'],
  ['Gap Fill', 'Mean reversion', 'Reviews movement back toward a prior close after a gap.'],
  ['Inside Bar Breakout', 'Price action', 'Checks a break from an inside-bar range.'],
  ['Pin Bar Reversal', 'Price action', 'Reviews rejection-wick context at a marked level.'],
  ['Engulfing Reversal', 'Price action', 'Checks a confirming engulfing candle pattern.'],
  ['Three-Bar Reversal', 'Price action', 'Reviews a three-bar reversal sequence.'],
  ['Bull Flag', 'Continuation', 'Checks consolidation and continuation after an impulse.'],
  ['Bear Flag', 'Continuation', 'Checks consolidation and continuation after a decline.'],
  ['Ascending Triangle', 'Breakout', 'Reviews a break from converging rising support.'],
  ['Descending Triangle', 'Breakout', 'Reviews a break from converging falling resistance.'],
  ['Cup and Handle', 'Continuation', 'Checks a handle break after a rounded base.'],
  ['Head and Shoulders', 'Reversal', 'Reviews a neckline break from a defined pattern.'],
  ['Double Top', 'Reversal', 'Checks rejection of a repeated high.'],
  ['Double Bottom', 'Reversal', 'Checks support at a repeated low.'],
  ['Mean Reversion Z-Score', 'Mean reversion', 'Reviews a return from a statistically extended move.'],
  ['Pairs Spread Reversion', 'Relative value', 'Checks spread movement toward a recorded mean.'],
  ['Seasonality Window', 'Calendar', 'Reviews behavior within a pre-defined calendar window.'],
  ['Relative Strength Rotation', 'Relative value', 'Checks relative performance between selected instruments.'],
  ['ATR Volatility Breakout', 'Volatility', 'Reviews a range break scaled by average true range.'],
  ['ATR Trailing Exit', 'Risk process', 'Checks whether an exit followed a defined ATR trail.'],
  ['Range Expansion', 'Volatility', 'Reviews expansion from a compressed trading range.'],
  ['Market Structure Shift', 'Price action', 'Checks a confirmed change in swing structure.'],
  ['Liquidity Sweep Reversal', 'Price action', 'Reviews rejection after a marked liquidity sweep.'],
  ['Fair Value Gap Retest', 'Price action', 'Checks a retest of a documented price imbalance.'],
].map(([name, family, summary]) => ({ name, family, summary }))
